language: "node_js"
node_js:
  - "10"
  - "12"
  - "14"
  - "14"
branches:
  only:
    - master
jobs:
  include:
    - stage: release
      if: branch = master AND type != pull_request
      node_js: lts/*
      script: skip
      after_success: skip
      deploy:
        provider: script
        cleanup: true
        script: npx semantic-release
script:
  - npm test
after_success:
  - npm i coveralls -D
  - node node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
