sudo: false
language: "node_js"
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "lts/*"
  - "node"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - npm run test
after_success:
  - npm i coveralls -D
  - node node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
