sudo: false
language: "node_js"
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
branches:
  only:
    - master
script:
  - npm run test
after_success:
  - npm i coveralls -D
  - node node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
